### ISSUE TITLE
Can only run with inline mode on gitlab

### ISSUE THREAD

**Issue by ppowell2** [mataku/danger-ktlint#9]
Hi,

I think there's another issue that alludes to this issue but doesn't provide much context. When running with inline_mode: false the ktlint plugin fails as it appears to reference a github api [here](https://github.com/mataku/danger-ktlint/blob/b698080521108346cd7a9c0512f81a81a7bea3db/lib/ktlint/plugin.rb#L70).

Output from danger:
```
Did you mean?  gitlab
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/plugin_support/plugin.rb:24:in `method_missing'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:70:in `block (3 levels) in send_markdown_comment'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:66:in `each'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:66:in `block (2 levels) in send_markdown_comment'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:65:in `each'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:65:in `block in send_markdown_comment'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:63:in `catch'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:63:in `send_markdown_comment'
	from /usr/local/bundle/gems/danger-ktlint-0.0.5/lib/ktlint/plugin.rb:42:in `lint'
	from Dangerfile:4:in `eval_file'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:311:in `eval'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:311:in `eval_file'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:204:in `block in parse'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:201:in `instance_eval'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:201:in `parse'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:287:in `run'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/danger_core/executor.rb:29:in `run'
	from /usr/local/bundle/gems/danger-8.4.2/lib/danger/commands/runner.rb:73:in `run'
	from /usr/local/bundle/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
	from /usr/local/bundle/gems/danger-8.4.2/bin/danger:5:in `<top (required)>'
	from /usr/local/bundle/bin/danger:25:in `load'
	from /usr/local/bundle/bin/danger:25:in `<main>'
```

Happy to help debug or provide more info

Thanks

**Comment by mataku** [comment]
@ppowell2 
Thanks for your report. I forgot that this library depended on `github` of Danger. It's not currently available, but I'll look into it and take care of it when I have more time.

https://github.com/mataku/danger-ktlint/issues/8 📝

**Comment by mataku** [comment]
@ppowell2 
Released as https://rubygems.org/gems/danger-ktlint/versions/0.0.6. Could you try v0.0.6 and let me know if there are any problems?
